uslingborg.zip : run_game.* README.txt screenshot.png src/*.py data/* data/fonts/*/*
	cd ..
	zip uslingborg/uslingborg.zip uslingborg/run_game.* uslingborg/README.txt uslingborg/screenshot.png uslingborg/src/*.py uslingborg/data/* uslingborg/data/fonts/*/*
	cd uslingborg

